a

diff --git a/.github/workflows/build-unity.yml b/.github/workflows/build-unity.yml
--- a/.github/workflows/build-unity.yml
+++ b/.github/workflows/build-unity.yml
@@ -31,22 +31,39 @@ on:
     outputs:
       artifact_name:
         description: "The name of the build artifact"
-        value: ${{ jobs.build.outputs.artifact_name }}
+        value: ${{ jobs.init.outputs.artifact_name }}
 
 jobs:
-  build:
-    name: Run the build for ${{ inputs.build_target_name }}
+  init:
+    name: Initialize before build
     runs-on: ubuntu-latest
 
     outputs:
       artifact_name: ${{ steps.vars.outputs.artifact_name }}
+      build_target: ${{ steps.vars.outputs.build_target }}
 
     steps:
-      # 仮想環境にクローン
-      - name: Check out my unity project
-        uses: actions/checkout@v4
-        with:
-          lfs: true
+      - name: check_env
+        run: |
+          isError=false
+          if [ -z ${{ secrets.UNITY_EMAIL }} ]; then
+            echo "::error::UNITY_EMAILが設定されていません"
+            isError=true
+          fi
+
+          if [ -z ${{ secrets.UNITY_PASSWORD }} ]; then
+            echo "::error::UNITY_PASSWORDが設定されていません"
+            isError=true
+          fi
+
+          if [ -z ${{ secrets.UNITY_LICENSE }} ]; then
+            echo "::error::UNITY_LICENSEが設定されていません"
+            isError=true
+          fi
+
+          if $isError ; then
+            exit 1
+          fi
 
       # ビルドターゲットに応じて環境変数を設定
       - name: Set Build Variables
@@ -56,10 +73,10 @@ jobs:
 
           # inputs.build_target_name に応じて build_target (プラットフォーム名) を設定
           if [ "${{ inputs.build_target_name }}" == "Windows" ]; then
-            echo "build_target=StandaloneWindows64" >> $GITHUB_ENV
+            echo "build_target=StandaloneWindows64" >> $GITHUB_OUTPUT
 
           elif [ "${{ inputs.build_target_name }}" == "WebGL" ]; then
-            echo "build_target=WebGL" >> $GITHUB_ENV
+            echo "build_target=WebGL" >> $GITHUB_OUTPUT
           else
             echo "Error: Invalid build_target_name."
             exit 1
@@ -67,8 +84,23 @@ jobs:
 
           # ARTIFACT_NAME を設定
           ARTIFACT_NAME_VALUE="${{ inputs.build_target_name }}-Build-$(git rev-parse --short HEAD)"
-          echo "ARTIFACT_NAME=${ARTIFACT_NAME_VALUE}" >> $GITHUB_ENV
           echo "artifact_name=${ARTIFACT_NAME_VALUE}" >> $GITHUB_OUTPUT
+
+  build:
+    name: Run the build for ${{ inputs.build_target_name }}
+    runs-on: ubuntu-latest
+    needs: init
+    env:
+      ARTIFACT_NAME: ${{ needs.init.outputs.artifact_name }}
+      BUILD_TARGET: ${{ needs.init.outputs.build_target }}
+      REPO_NAME: ${{ github.event.repository.name }}
+
+    steps:
+      # 仮想環境にクローン
+      - name: Check out my unity project
+        uses: actions/checkout@v4
+        with:
+          lfs: true
 
       # Unityビルドの前にランナーの空き容量を確保する
       - name: Free Disk Space
@@ -110,20 +142,20 @@ jobs:
           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         with:
-          buildName: ${{ github.event.repository.name }}
-          targetPlatform: ${{ env.build_target }}
+          buildName: ${{ env.REPO_NAME }}
+          targetPlatform: ${{ env.BUILD_TARGET }}
           allowDirtyBuild: true
 
       # ビルド成果物をアップロード
       - name: Upload the build for GitHub Pages
-        if: inputs.build_target_name == 'WebGL'
+        if: env.BUILD_TARGET == 'WebGL'
         uses: actions/upload-pages-artifact@v4
         with:
           name: github-pages
-          path: build/${{ env.build_target }}/${{ github.event.repository.name }}
+          path: build/${{ env.BUILD_TARGET }}/${{ env.REPO_NAME }}
 
       - name: Upload the Build
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.ARTIFACT_NAME }}
-          path: build/${{ env.build_target }}
+          path: build/${{ env.BUILD_TARGET }}
